FROM eclipse-temurin:17.0.4.1_1-jre

WORKDIR /app

COPY ./ /app/tachyons

EXPOSE 30303

WORKDIR /app/tachyons/server

RUN echo '#!/bin/bash\n\
java -jar TachyonsServer.jar' > /app/start.sh && \
    chmod +x /app/start.sh

CMD ["/app/start.sh"]
